In [1]:
from rrt_star import *
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import roboticstoolbox as rtb
import spatialmath as sm # provides objects for representing transformations
from swift import Swift # lightweight browser-based simulator which comes with the toolbox
import spatialgeometry as sg # utility package for dealing with geometric objects

In [3]:
robot = rtb.models.wx200()
print(robot)

moving_link_idxs = [0,1,2,3,4]
colliding_link_idxs  = [0,1,2,3,4,5,6,7,8,9,10,11,12]

def pad(q):
	return np.hstack([q, [0]*(len(robot.q)-len(moving_link_idxs))])

ERobot: wx200 (by Interbotix), 8 joints (RRRRRRPP), 4 branches, dynamics, geometry, collision
┌──────┬─────────────────────┬───────┬───────────────────┬───────────────────────────────────────────┐
│ link │        link         │ joint │      parent       │            ETS: parent to link            │
├──────┼─────────────────────┼───────┼───────────────────┼───────────────────────────────────────────┤
│    0 │ /base_link          │       │ BASE              │ SE3()                                     │
│    1 │ /shoulder_link      │     0 │ /base_link        │ SE3(0, 0, 0.0716) ⊕ Rz(q0)                │
│    2 │ /upper_arm_link     │     1 │ /shoulder_link    │ SE3(0, 0, 0.03865) ⊕ Ry(q1)               │
│    3 │ /forearm_link       │     2 │ /upper_arm_link   │ SE3(0.05, 0, 0.2; 180°, -0°, 0°) ⊕ Ry(q2) │
│    4 │ /wrist_link         │     3 │ /forearm_link     │ SE3(0.2, 0, 0) ⊕ Ry(q3)                   │
│    5 │ /gripper_link       │     4 │ /wrist_link       │ SE3(0.065, 0, 0; -180°,

In [4]:
sp = sg.Sphere(0.2)
sp.T = sp.T * sm.SE3.Trans(0,0.4,0.6)
obstacles = [sp]

def has_collision(q):
	robot.q = pad(q)
	links = [robot.links[i] for i in colliding_link_idxs]
	n_links = len(links)
	for i1 in range(n_links):
		link1 = links[i1]

		# check if this link collides with any obstacles
		for obstacle in obstacles:
			for collider in link1.collision:
				if collider.iscollided(obstacle):
					print(f'found a collision between (link {link1}) and ({obstacle})')
					return True

		# check if this link collides with any other links
		for i2 in range(n_links):
			if abs(i1-i2)<2:
				continue # don't check adjacent links
			link2 = links[i2]
			for collider1 in link1.collision:
				if collider1.stype == 'mesh':
					continue
				for collider2 in link2.collision:
					if collider2.stype == 'mesh':
						continue
					if collider1.iscollided(collider2):
						return True
	return False

# has_collision(robot.q[moving_link_idxs])

In [5]:
goal_ee_T = robot.fkine((1/4*robot.qlim[0]+3/4*robot.qlim[1]), end='/ee_arm_link')
goal_estimate = robot.ikine_QP(Tep=goal_ee_T, end='/ee_arm_link').q

def goal_test(q):
	ee_T = robot.fkine(pad(q), end='/ee_arm_link')
	return np.sum(np.abs(ee_T-goal_ee_T)) < 0.01

In [6]:
start_config = np.zeros(len(moving_link_idxs)) # Initial configuration

planner = RRTStar(start=start_config, goal=goal_estimate, 
					minCoords=robot.qlim[0][moving_link_idxs], maxCoords=robot.qlim[1][moving_link_idxs], 
					goal_test=goal_test, step_size=0.1, search_radius=0.4, collisionChecker=has_collision)
path = planner.run_rrt_star()

if path:
	print("Found path:")
	for config in path:
		print(config)
else:
	print("Path not found.")

pybullet build time: Nov 28 2023 23:45:17


Goal reached in 377 iterations.
Found path:
[0. 0. 0. 0. 0.]
[ 0.26903754  0.09627276  0.01124591 -0.05317545  0.149173  ]
[ 0.52698709  0.11714327  0.14678909 -0.01710526  0.27309666]
[0.7280459  0.2383968  0.10770613 0.139356   0.51888353]
[0.89664238 0.41121689 0.20824887 0.28980343 0.69234339]
[1.09769591 0.51618153 0.3611139  0.32804145 0.82217009]
[1.2412467  0.69963089 0.59128106 0.36181086 1.02475833]
[1.35591572 0.80664517 0.79333163 0.53535254 1.25495302]
[1.5172393  0.94118051 0.93945974 0.67893033 1.46897553]
[1.54513211 0.98509639 0.99370211 0.71816157 1.5220044 ]
[1.57079633 1.02550345 1.04361057 0.75425829 1.57079633]
[1.57079633 1.02550345 1.04361057 0.75425829 1.57079633]


In [7]:
ee_axes = sg.Axes(0.1)
goal_axes = sg.Axes(0.1)
goal_axes.T = goal_ee_T

# Make a new environment and add our robot
env = Swift()
env.launch(realtime=True, browser="notebook")
env.add(robot)
env.add(ee_axes)
env.add(goal_axes)
env.add(sp)

# Change the robot configuration to the ready position
robot.q = pad(start_config)

# Step the sim to view the robot in this configuration
env.step(0.01)

dt = 0.75
time = 0

for step_i in range(len(path)):
	robot.q = pad(path[step_i])

	if has_collision(robot.q[moving_link_idxs]):
		print('found collision at step', step_i)
	
	# Update the ee axes
	ee_axes.T = robot.fkine(robot.q, end='/ee_arm_link').A
	
	# Step the simulator by dt seconds
	env.step(dt)
	time += dt